receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
 
  debug:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]